inherit_gem:
  fincop:
    - 'config/rails.yml'
    - 'config/rspec.yml'
    - 'config/rubocop.yml'
    - 'config/performance.yml'
    # If you are using Rails 4, activate this cop.
    # - 'config/disabled_for_rails_4.yml'

AllCops:
  TargetRubyVersion: 2.7
